/**
 * Copyright 2023 Dremio
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dremio.support.diagnostics.stress;

import java.util.Objects;

/** api call response */
public class DremioApiResponse {
  private String errorMessage;
  private boolean created;

  /**
   * sets the error message on the response
   *
   * @param errorMessage error message that occurred during this operation.
   */
  public void setErrorMessage(final String errorMessage) {
    this.errorMessage = errorMessage;
  }

  /**
   * setter on created
   *
   * @param created boolean was it created or not
   */
  public void setCreated(final boolean created) {
    this.created = created;
  }

  /**
   * Gets the created status of the request
   *
   * @return if request was successful or not
   */
  public boolean isCreated() {
    return created;
  }

  /**
   * gets error message generated by api response.
   *
   * @return error message generated by api response
   */
  public String getErrorMessage() {
    return errorMessage;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof DremioApiResponse)) return false;
    DremioApiResponse that = (DremioApiResponse) o;
    return created == that.created && Objects.equals(errorMessage, that.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorMessage, created);
  }
}
