#!/bin/sh

# scripts/build: build jar
set -e

cd "$(dirname "$0")/.."
./mvnw validate
./mvnw clean package -DskipTests=true
mv $(ls target/dremio-stress-*-jar-with-dependencies.jar) target/dremio-stress.jar
